/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MaterialResources } from '../../models/material-resources';

export interface UpdateMaterial$Params {
  idMR: number;
      body: MaterialResources
}

export function updateMaterial(http: HttpClient, rootUrl: string, params: UpdateMaterial$Params, context?: HttpContext): Observable<StrictHttpResponse<MaterialResources>> {
  const rb = new RequestBuilder(rootUrl, updateMaterial.PATH, 'put');
  if (params) {
    rb.path('idMR', params.idMR, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MaterialResources>;
    })
  );
}

updateMaterial.PATH = '/MaterialResources/updateMaterial/{idMR}';
