pipeline {
    agent any

    stages {
        stage('Checkout Git') {
            steps {
                // Simple checkout Git
                git branch: 'main', url: 'https://github.com/dhiakh14/pi.git'
            }
        }

        stage('Build') {
            steps {
                echo "Le code a été récupéré avec succès !"
            }
        }
    }
}
