pipeline {
    agent any
    options { skipDefaultCheckout() } // prevents Jenkins from automatically checking out the repo

    stages {
        stage('Git') {
            steps {
                script {
                    bat 'git config --global http.postBuffer 524288000'
                    bat 'git config --global core.compression 0'

                    checkout([$class: 'GitSCM',
                      branches: [[name: '*/main']],
                      userRemoteConfigs: [[
                        url: 'https://github.com/dhiakh14/pi.git',
                        credentialsId: 'git-token'
                      ]],
                      extensions: [
                          [$class: 'CloneOption', depth: 1, timeout: 20, honorRefspec: true, noTags: true],
                          [$class: 'PruneStaleBranch']
                      ]
                    ])
                }
            }
        }

        }

        stage('Maven Build') {
            steps { bat 'mvn clean install' }
        }

        stage('Test') {
            steps { bat 'mvn test' }
        }
    }
}
