/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { HumanResources } from './models/human-resources';
export { MaterialResources } from './models/material-resources';
