/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { MaterialResourcesRestControllerService } from './services/material-resources-rest-controller.service';
export { HumanResourcesRestControllerService } from './services/human-resources-rest-controller.service';
export { GeminiControllerService } from './services/gemini-controller.service';
