import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { MaterialResources } from 'src/app/ServiceMaram/models';
import { MaterialResourcesRestControllerService } from 'src/app/ServiceMaram/services';

@Component({
  selector: 'app-add-mat',
  templateUrl: './add-mat.component.html',
  styleUrls: ['./add-mat.component.css']
})
export class AddMatComponent {
  // Initialize a new MaterialResources object
  materialResource: Partial<MaterialResources> = {
    idMR: 0, // This will be auto-generated by the backend
    category: 'CONSTRUCTION_MATERIAL', // Default category
    firstName: '',
    price: 0,
    quantity: 0
  };

  constructor(
    private materialService: MaterialResourcesRestControllerService,
    private router: Router
  ) {}

  // Handle form submission
  addMaterial() {
    // Validate required fields
    if (!this.materialResource.firstName || !this.materialResource.price || !this.materialResource.quantity) {
      alert('First Name, Price, and Quantity are required!');
      return;
    }

    // Call the service to add the MaterialResources entity
    this.materialService.addmat({ body: this.materialResource as MaterialResources }).subscribe(
      (response) => {
        console.log('Material Resource added successfully:', response);
        alert('Material Resource added successfully!');
        this.router.navigate(['/matlist']); // Navigate to the materials list page
      },
      (error) => {
        console.error('Error adding Material Resource:', error);
        alert('Failed to add Material Resource. Please try again.');
      }
    );
  }

  // Handle cancel button click
  cancel() {
    this.router.navigate(['/matlist']); // Navigate back to the materials list page
  }
}