/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HumanResources {
  availability: boolean;
  email: string;
  idHR: number;
  job_Role: 'MASON' | 'ELECTRICIAN' | 'PLUMBER';
  lastName: string;
  name: string;
  phoneNumber: number;
}
