/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MaterialResources {
  category: 'CONSTRUCTION_MATERIAL' | 'EQUIPMENT_AND_MACHINES' | 'TOOLS' | 'VEHICLES' | 'SECURITY';
  firstName: string;
  idMR: number;
  price: number;
  quantity: number;
}
