/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectDto {
  complexity_encoded?: number;
  duration_days?: number;
  estimated_budget_kdt?: number;
  team_size?: number;
}
