/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HumanResources } from '../../models/human-resources';

export interface AddHr$Params {
      body: HumanResources
}

export function addHr(http: HttpClient, rootUrl: string, params: AddHr$Params, context?: HttpContext): Observable<StrictHttpResponse<HumanResources>> {
  const rb = new RequestBuilder(rootUrl, addHr.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HumanResources>;
    })
  );
}

addHr.PATH = '/HumanResources/addHR';
